name: Laravel Project ci

on:
  push:
    branches: ["master"]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ vars.DB_DATABASE }}
          POSTGRES_USER: ${{ vars.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ vars.DB_PASSWORD }}
        ports:
          - ${{ vars.DB_PORT }}:${{ vars.DB_PORT }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:        
    - name: Checkout project dir
      uses: actions/checkout@v3
  
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Create .env
      run: |
        touch .env
        chmod -R 777 .env
        
        echo "${{ vars.ENV_FILE }}" >> .env
        echo DB_DATABASE="${{ vars.DB_DATABASE }}" >> .env
        echo DB_USERNAME="${{ vars.DB_USERNAME }}" >> .env
        echo DB_PASSWORD="${{ vars.DB_PASSWORD }}" >> .env
        echo DB_PORT="${{ vars.DB_PORT }}" >> .env
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Migration
      run: php artisan migrate
        
    - name: Execute tests (Unit and Feature tests) via artisan
      run: php artisan test
