name: Laravel Project ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0000
          POSTGRES_DB: test-orm-n
        ports:
          - 5432:5432

    steps:        
    - name: Checkout project dir
    - uses: actions/checkout@v3
  
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Create .env
#       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      run: echo "${{ vars.ENV_FILE }}" >> .env
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Migration
      run: php artisan migrate
        
    - name: Execute tests (Unit and Feature tests) via artisan
      run: php artisan test
